#!/usr/bin/env python
"""Generate Phase 2 variants from Phase 1's comparison.json.

Phase 2 design (option C — full picture):
  1 mono  × winner             (the winning ≥7B coder from Phase 1)
  1 swarm × matched winner     (same model in worker tier)
  1 swarm × best-small          (qwen-coder-1.5b by default; --small to override)
  1 micro × matched winner     (same model in drafter/coder)
  1 micro × best-small          (small drafter — the microloop thesis test)

= 5 variants × 5 fixtures = 25 runs in Phase 2.

Usage:
  # After Phase 1 finishes:
  python scripts/generate_phase2_variants.py
  python scripts/generate_phase2_variants.py --input acceptance/phase1/comparison.json
  python scripts/generate_phase2_variants.py --small qwen-coder-0.5b

Winner selection (deterministic):
  1. Highest fixtures passed
  2. Tiebreak: highest score (currently same metric as passed for these fixtures)
  3. Tiebreak: lowest avg wall_s
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Known small candidates from the small-model bake-off (kept for reference).
SMALL_MODELS = {
    "qwen-coder-0.5b": "Qwen2.5-Coder-0.5B-Instruct-4bit",
    "qwen-coder-1.5b": "Qwen2.5-Coder-1.5B-Instruct-4bit",
}


def pick_mono_winner(comparison_data: dict) -> tuple[str, str, dict]:
    """Return (variant_id, model_label, row_dict) for the best mono variant."""
    rows = comparison_data.get("variants", {})
    mono_rows = {vid: row for vid, row in rows.items() if vid.startswith("mono__")}
    if not mono_rows:
        raise ValueError("No mono__* variants in comparison.json — was Phase 1 run?")

    def sort_key(item):
        vid, row = item
        # Negate passed/score so max sorts first; positive wall_s so min sorts first.
        passed = row.get("passed", 0)
        score = row.get("score", 0) if "score" in row else passed
        wall = row.get("avg_wall_s", 1e9)
        return (-passed, -score, wall)

    sorted_rows = sorted(mono_rows.items(), key=sort_key)
    winner_vid, winner_row = sorted_rows[0]
    model_label = winner_vid[len("mono__"):]
    return winner_vid, model_label, winner_row


# Map known model_label → oMLX model_id. Phase 1 variants file is the source
# of truth, so we read it back to avoid duplicating IDs here.
def load_phase1_label_to_id(phase1_path: Path) -> dict[str, str]:
    import yaml
    raw = yaml.safe_load(phase1_path.read_text()) or {}
    return {v["model_label"]: v["model_id"] for v in (raw.get("variants") or [])}


def emit_yaml(variants: list[dict]) -> str:
    lines = [
        "# Phase 2: head-to-head — Phase 1 mono winner vs swarm vs micro,",
        "# with both matched (same model in worker tier) and small (best-of-bake-off",
        "# small coder) configurations. Auto-generated by",
        "# scripts/generate_phase2_variants.py from Phase 1's comparison.json.",
        "#",
        "# Run:  python -m benchmarks.maintain_suite.run \\",
        "#         --variants benchmarks/maintain_suite/variants_phase2_compare.yaml \\",
        "#         --output acceptance/phase2 --all",
        "",
        "variants:",
    ]
    for v in variants:
        lines.append(
            f"  - {{mode: {v['mode']}, "
            f"model_label: {v['model_label']}, "
            f"model_id: {v['model_id']}}}"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input", type=Path,
                    default=ROOT / "acceptance" / "phase1" / "comparison.json",
                    help="Phase 1 comparison.json path")
    ap.add_argument("--phase1-variants", type=Path,
                    default=ROOT / "benchmarks" / "maintain_suite" / "variants_phase1_mono.yaml",
                    help="Phase 1 variants file (used to resolve label → model_id)")
    ap.add_argument("--output", type=Path,
                    default=ROOT / "benchmarks" / "maintain_suite" / "variants_phase2_compare.yaml",
                    help="Where to write the Phase 2 variants file")
    ap.add_argument("--small", default="qwen-coder-1.5b",
                    choices=list(SMALL_MODELS.keys()),
                    help="Small candidate to fill the swarm/micro worker tier "
                         "(default: qwen-coder-1.5b — clean schema, made tool calls "
                         "in both modes during the prior small-model bake-off)")
    args = ap.parse_args()

    if not args.input.is_file():
        print(f"[error] {args.input} not found — run Phase 1 first.", file=sys.stderr)
        print(f"  python -m benchmarks.maintain_suite.run \\", file=sys.stderr)
        print(f"    --variants {args.phase1_variants} \\", file=sys.stderr)
        print(f"    --output acceptance/phase1 --all", file=sys.stderr)
        return 2

    data = json.loads(args.input.read_text())
    winner_vid, winner_label, winner_row = pick_mono_winner(data)
    label_to_id = load_phase1_label_to_id(args.phase1_variants)
    if winner_label not in label_to_id:
        print(f"[error] mono winner '{winner_label}' not found in {args.phase1_variants}",
              file=sys.stderr)
        return 3
    winner_id = label_to_id[winner_label]

    print(f"Phase 1 winner: [bold]{winner_vid}[/]  "
          f"passed={winner_row.get('passed')}  "
          f"avg_wall={winner_row.get('avg_wall_s')}s  "
          f"avg_tok={winner_row.get('avg_tokens')}")
    print()
    print("Mono runner-ups:")
    rows = data.get("variants", {})
    mono_rows = {vid: row for vid, row in rows.items() if vid.startswith("mono__")}
    for vid, row in sorted(mono_rows.items()):
        marker = " ← winner" if vid == winner_vid else ""
        print(f"  {vid:30s}  passed={row.get('passed', 0)}  "
              f"wall={row.get('avg_wall_s', 0)}s{marker}")

    small_id = SMALL_MODELS[args.small]

    variants = [
        {"mode": "mono",  "model_label": winner_label, "model_id": winner_id},
        {"mode": "swarm", "model_label": winner_label, "model_id": winner_id},
        {"mode": "swarm", "model_label": args.small,   "model_id": small_id},
        {"mode": "micro", "model_label": winner_label, "model_id": winner_id},
        {"mode": "micro", "model_label": args.small,   "model_id": small_id},
    ]

    args.output.write_text(emit_yaml(variants))
    print()
    print(f"Wrote {args.output}")
    print(f"  5 variants × N fixtures = Phase 2 run plan")
    print(f"  - mono__{winner_label}   (Phase 1 winner)")
    print(f"  - swarm__{winner_label}  (matched: same model in worker tier)")
    print(f"  - swarm__{args.small}    (small worker — bake-off best)")
    print(f"  - micro__{winner_label}  (matched: same model in drafter/coder)")
    print(f"  - micro__{args.small}    (small drafter — the microloop thesis test)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
